<?php
/**
 * Veritrans VT Direct virtual account Model Standard
 *
 * @category   Mage
 * @package    permatava/form.phtml
 * this template is rendered when Veritrans payment method is chosen. This is description about Veritrans Payment Method
 */
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
	Pay with BCA Klikpay
	</li>
</ul>
